### ISSUE TITLE
docker.io/omicsclass/genome-comparison:v1.0

### ISSUE THREAD

**Issue by ccchendong** [DaoCloud/public-image-mirror#10212]
IMAGE SYNC

**Comment by babaowin** [comment]
I used podman pull m.daocloud.io/docker.io/omicsclass/genome-comparison:v1.0 to pull the image, but I encountered an error. What should I do?

**Comment by babaowin** [comment]
Trying to pull m.daocloud.io/docker.io/omicsclass/genome-comparison:v1.0...
WARN[0000] failed, retrying in 1s ... (1/3). Error: initializing source docker://m.daocloud.io/docker.io/omicsclass/genome-comparison:v1.0: reading manifest v1.0 in m.daocloud.io/docker.io/omicsclass/genome-comparison: denied: 🚫 这镜像不在白名单. this image is not in the allowlist. 📦 https://github.com/DaoCloud/public-image-mirror/issues/2328 🔗
WARN[0001] failed, retrying in 1s ... (2/3). Error: initializing source docker://m.daocloud.io/docker.io/omicsclass/genome-comparison:v1.0: reading manifest v1.0 in m.daocloud.io/docker.io/omicsclass/genome-comparison: denied: 🚫 这镜像不在白名单. this image is not in the allowlist. 📦 https://github.com/DaoCloud/public-image-mirror/issues/2328 🔗
WARN[0003] failed, retrying in 1s ... (3/3). Error: initializing source docker://m.daocloud.io/docker.io/omicsclass/genome-comparison:v1.0: reading manifest v1.0 in m.daocloud.io/docker.io/omicsclass/genome-comparison: denied: 🚫 这镜像不在白名单. this image is not in the allowlist. 📦 https://github.com/DaoCloud/public-image-mirror/issues/2328 🔗
Error: initializing source docker://m.daocloud.io/docker.io/omicsclass/genome-comparison:v1.0: reading manifest v1.0 in m.daocloud.io/docker.io/omicsclass/genome-comparison: denied: 🚫 这镜像不在白名单. this image is not in the allowlist. 📦 https://github.com/DaoCloud/public-image-mirror/issues/2328 🔗

**Comment by wzshiming** [comment]
https://hub.docker.com/r/omicsclass/genome-comparison

This image does removed or is private

@babaowin
