### ISSUE TITLE
add registry.k8s.io

### ISSUE THREAD

**Issue by yankay** [DaoCloud/public-image-mirror#103]
Accroding to the https://github.com/kubernetes/kubeadm/pull/2670.

k8s would use registry.k8s.io.

**Comment by yankay** [comment]
![2ce8c10c-8db6-4eb8-ba1c-a832f6740db2](https://user-images.githubusercontent.com/1469319/160321108-be7a11c0-af31-4433-bdd3-3d0e627f9acf.png)

**Comment by kerthcet** [comment]
Any progress on this? `registry.k8s.io` was introduced to Kubernetes core package already.

**Comment by wzshiming** [comment]
I forgot...  
Help me change the A record of `k8s.m.daocloud.io` to `113.31.147.179`

@yankay

**Comment by wzshiming** [comment]
https://github.com/DaoCloud/public-image-mirror/pull/163
