### ISSUE TITLE
docker pull m.daocloud.io/docker.io/onlyoffice/documentserver:7.1.1

### ISSUE THREAD

**Issue by 12341234-yangboran** [DaoCloud/public-image-mirror#11294]
![image](https://github.com/DaoCloud/public-image-mirror/assets/74187378/ba0a3316-1973-4cb2-9476-866636215fe3)
请问我的拉取方式是否有问题?

**Comment by 12341234-yangboran** [comment]
![image](https://github.com/DaoCloud/public-image-mirror/assets/74187378/9a82fbb9-413b-46d6-94da-3bfcc00d0e4e)

**Comment by wzshiming** [comment]
没有问题, 就是有限流, https://github.com/DaoCloud/public-image-mirror/issues/6196

**Comment by 12341234-yangboran** [comment]
我看这个镜像之前已经同步了，请问有什么方法可以解决限流问题

**Comment by wzshiming** [comment]
我看了下镜像大约 1G 多, 讲道理卡个 30 分钟应该就开始下载了啊

**Comment by 12341234-yangboran** [comment]
好，我再试一下

**Comment by 12341234-yangboran** [comment]
请问我应该如何配置registry-mirrors

**Comment by wzshiming** [comment]
https://github.com/DaoCloud/public-image-mirror?tab=readme-ov-file#%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5
