### ISSUE TITLE
利用GitHub action，快速同步任意镜像，实现镜像快速pull，不限速

### ISSUE THREAD

**Issue by imdingtalk** [DaoCloud/public-image-mirror#12319]
项目地址：  
https://github.com/imdingtalk/image-mirror
介绍：  
支持同步所有外部镜像到国内任意仓库，从而实现快速下载镜像
使用方法：
1. 直接提交issue，标题随意，内容直接填写你无法pull的任意外部公网镜像就行，不限制外部是哪个仓库的
2. 或者fork仓库，同步镜像到自己的目标仓库，在自己的仓库内提交issue

**Comment by chenxiang0808** [comment]
https://hub.docker.com/r/talebook/talebook

**Comment by hanxianzhai** [comment]
ghcr.io/zitadel/zitadel:v2.54.3
