### ISSUE TITLE
docker.io/hanxi/xiaomusic

### ISSUE THREAD

**Issue by newrookie001** [DaoCloud/public-image-mirror#13404]
### 要同步的级别

需要这个组织下所有镜像 (如 docker.io/library/**) (要求是开源项目的组织)

### Source

https://github.com/hanxi/xiaomusic

### Dockerfile

https://hub.docker.com/layers/hanxi/xiaomusic/latest/images/sha256-4946144633a2f5aee2c962cfe60a23a245e7c4ceb7d5a4880bd7201525a9fdb6?context=explore

### Image

https://hub.docker.com/r/hanxi/xiaomusic

**Comment by wzshiming** [comment]
建议放国内镜像仓库 https://github.com/DaoCloud/public-image-mirror/issues/2328
