### ISSUE TITLE
docker pull k8s.gcr.io的镜像

### ISSUE THREAD

**Issue by QiuToo** [DaoCloud/public-image-mirror#135]
如何设置镜像代理，实现docker pull来下载k8s.gcr.io的镜像

**Comment by JaredTan95** [comment]
请阅读仓库 Readme https://github.com/DaoCloud/public-image-mirror#%E6%9B%BF%E6%8D%A2%E8%A7%84%E5%88%99 `k8s-gcr.m.daocloud.io`
