### ISSUE TITLE
https://hub.docker.com/r/makedie/fastapi-dls

### ISSUE THREAD

**Issue by Hhh-YC** [DaoCloud/public-image-mirror#13629]
### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox) (要求满足下面的内容)

### Source

https://hub.docker.com/r/makedie/fastapi-dls

### Dockerfile

https://hub.docker.com/r/makedie/fastapi-dls

### Image

https://hub.docker.com/r/makedie/fastapi-dls

**Comment by wzshiming** [comment]
建议放国内镜像仓库 https://github.com/DaoCloud/public-image-mirror/issues/2328
