### ISSUE TITLE
docker.io/xiaoyaliu/alist:latest

### ISSUE THREAD

**Issue by bjs2333** [DaoCloud/public-image-mirror#13685]
### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox) (要求满足下面的内容)

### Source

docker.io/xiaoyaliu/alist:latest

### Dockerfile

docker.io/xiaoyaliu/alist:latest

### Image

docker.io/xiaoyaliu/alist:latest

**Comment by wzshiming** [comment]
建议放国内镜像仓库 https://github.com/DaoCloud/public-image-mirror/issues/2328
