### ISSUE TITLE
增加 determinedai

### ISSUE THREAD

**Issue by KyanChen** [DaoCloud/public-image-mirror#13795]
### 要同步的级别

需要这个组织下所有镜像 (如 docker.io/library/**) (要求是开源项目的组织)

### Source

docker.io/determinedai/**

### Dockerfile

[docker.io/determinedai/**](https://hub.docker.com/r/determinedai)

### Image

[docker.io/determinedai/**](https://hub.docker.com/r/determinedai)

**Comment by wzshiming** [comment]
没找到源码

**Comment by KyanChen** [comment]
https://hub.docker.com/u/determinedai
