### ISSUE TITLE
xiaoyaliu/alist:hostmode

### ISSUE THREAD

**Issue by wgf520** [DaoCloud/public-image-mirror#13892]
### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### Source

https://hub.docker.com/r/xiaoyaliu/alist

### Dockerfile

https://hub.docker.com/r/xiaoyaliu/alist

### Image

https://hub.docker.com/r/xiaoyaliu/alist

**Comment by wzshiming** [comment]
建议放国内镜像仓库 https://github.com/DaoCloud/public-image-mirror/issues/2328
