### ISSUE TITLE
 请将cloudflare/cloudflared:latest加入白名单

### ISSUE THREAD

**Issue by zhoucheng8023** [DaoCloud/public-image-mirror#13906]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/cloudflare/cloudflared

### 官网 或 文档 或 项目源码 中哪提及对应的镜像 (需要证明这个镜像和源码有实际关联)

https://github.com/cloudflare/cloudflared?tab=readme-ov-file#installing-cloudflared

### 镜像仓库地址

https://github.com/cloudflare/cloudflared

**Comment by wzshiming** [comment]
已经有了
