### ISSUE TITLE
请求添加hub.docker.com/r/frooodle/s-pdf:latest至白名单

### ISSUE THREAD

**Issue by wangyan-samuel** [DaoCloud/public-image-mirror#13984]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/Stirling-Tools/Stirling-PDF

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://hub.docker.com/r/frooodle/s-pdf

### 镜像仓库地址

https://hub.docker.com/r/frooodle/s-pdf

### 补充说明

thanks a lot

**Comment by wzshiming** [comment]
已经有了
