### ISSUE TITLE
docker.io/idootop/mi-gpt:latest

### ISSUE THREAD

**Issue by wefeng998** [DaoCloud/public-image-mirror#14288]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/idootop/mi-gpt

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

Docker
Docker Image Version

对于电脑小白或者不想自己配置代码运行环境（Node）的同学，可以使用 Docker 启动方式。

请先按照 [⚙️ 参数设置](https://github.com/idootop/mi-gpt/blob/main/docs/settings.md) 相关说明，配置好你的 .env 和 .migpt.js 文件，然后使用以下命令启动 docker：

docker run -d --env-file $(pwd)/.env -v $(pwd)/.migpt.js:/app/.migpt.js idootop/mi-gpt:latest
注意：在 Windows 终端下需要将配置文件路径 $(pwd) 替换为绝对路径。

### 镜像仓库地址

https://hub.docker.com/r/idootop/mi-gpt

### 补充说明

无

**Comment by wzshiming** [comment]
建议放国内镜像仓库 https://github.com/DaoCloud/public-image-mirror/issues/2328
