### ISSUE TITLE
vimagick/tinyproxy:latest

### ISSUE THREAD

**Issue by chiwenheng** [DaoCloud/public-image-mirror#14300]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

[vimagick/tinyproxy:latest](https://github.com/tinyproxy)

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://tinyproxy.github.io/

### 镜像仓库地址

https://tinyproxy.github.io/

### 补充说明

轻量服务器代理

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328
