### ISSUE TITLE
请求添加docker.io/nastool/nas-tools:latest

### ISSUE THREAD

**Issue by JuizF** [DaoCloud/public-image-mirror#14307]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/NAStool/nas-tools

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

NAS媒体库管理工具

GitHub stars GitHub forks Platform

Docker：https://hub.docker.com/r/nastool/nas-tools

Wiki：https://wiki.nastool.org/

API：http://localhost:3000/api/v1/

### 镜像仓库地址

docker.io/nastool/nas-tools:latest

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328
