### ISSUE TITLE
docker.io/xiaoyaliu/alist:hostmode

### ISSUE THREAD

**Issue by xu19901120** [DaoCloud/public-image-mirror#14373]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

docker.io/xiaoyaliu/alist:hostmode

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

docker.io/xiaoyaliu/alist:hostmode

### 镜像仓库地址

docker.io/xiaoyaliu/alist:hostmode

**Comment by xu19901120** [comment]
小雅alist  谢谢

**Comment by wzshiming** [comment]
建议放国内镜像仓库 https://github.com/DaoCloud/public-image-mirror/issues/2328
