### ISSUE TITLE
docker.io/xuzhengze/tech-study-docker

### ISSUE THREAD

**Issue by chu0119** [DaoCloud/public-image-mirror#14612]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/Xu22Web/tech-study-node

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

拉取 docker 镜像，创建 tech-study-docker 容器

拉取 docker 镜像

docker pull xuzhengze/tech-study-docker
创建 tech-study-docker 容器

docker compose up -d

### 镜像仓库地址

https://docker.io/xuzhengze/tech-study-docker

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328
