### ISSUE TITLE
docker.io/

### ISSUE THREAD

**Issue by se072011** [DaoCloud/public-image-mirror#14628]
### 镜像是否符合下列要求

- [x] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/hsuyelin/nas-tools

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/hsuyelin/nas-tools

### 镜像仓库地址

docker pull hsuyelin/nas-tools:latest

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328
