### ISSUE TITLE
docker.io/stilleshan/frpc:latest

### ISSUE THREAD

**Issue by jaxwang** [DaoCloud/public-image-mirror#14682]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

源码地址: [https://github.com/stilleshan/frpc](https://github.com/stilleshan/frpc)
dockerhub地址: [https://hub.docker.com/r/stilleshan/frpc](https://hub.docker.com/r/stilleshan/frpc)

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/fatedier/frp
https://github.com/stilleshan/frpc

### 镜像仓库地址

https://hub.docker.com/r/stilleshan/frpc

### 补充说明

frp在内网穿透这个领域还是挺出名的,  stilleshan版本的镜像, 国人pull的比较多, frpc是客服端, 同样还有一个frps服务端的镜像,  地址是: https://hub.docker.com/r/stilleshan/frps

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328
