### ISSUE TITLE
aalkaswan/bint5

### ISSUE THREAD

**Issue by ljk419511** [DaoCloud/public-image-mirror#14816]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/AISE-TUDelft/Capybara-BinT5

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

> It is recommended to use the provided Docker image, which has the correct Cuda version and all of the required dependencies installed. Pull the image, create a container, and mount this folder as a volume:
> ```
> docker pull aalkaswan/bint5
> docker run -i -t --name {containerName} --gpus all -v $(pwd):/data aalkaswan/bint5 /bin/bash
> ```

### 镜像仓库地址

https://hub.docker.com/r/aalkaswan/bint5

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 https://github.com/DaoCloud/public-image-mirror/issues/2328
