### ISSUE TITLE
docker.io/lovechen/embyserver:latest

### ISSUE THREAD

**Issue by gleihow001** [DaoCloud/public-image-mirror#14868]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

需要这个镜像仓库下所有镜像 (如 registry.k8s.io/**)

### 项目源码地址 或 组织地址

docker.io/lovechen/embyserver:latest

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

docker.io/lovechen/embyserver:latest

### 镜像仓库地址

https://github.com/DaoCloud/public-image-mirror/issues/14863

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 https://github.com/DaoCloud/public-image-mirror/issues/2328
