### ISSUE TITLE
chishin/wol-go-web

### ISSUE THREAD

**Issue by spicyboy1984** [DaoCloud/public-image-mirror#15176]
### 镜像是否符合下列要求

- [X] 确认这个镜像符合要求

### 要同步的级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/xiaoxinpro/WolGoWeb

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/xiaoxinpro/WolGoWeb/blob/master/README.md

### 镜像仓库地址

https://hub.docker.com/r/chishin/wol-go-web/tags

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328 可以尝试其中别的方法 如 [快速部署自己的 Mirror](https://github.com/DaoCloud/crproxy/tree/master/examples/simple)
