### ISSUE TITLE
wener

### ISSUE THREAD

**Issue by wenerme** [DaoCloud/public-image-mirror#15908]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/wenerme/dockerfiles

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/wenerme/dockerfiles

### 镜像仓库地址

https://hub.docker.com/r/wener

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 https://github.com/DaoCloud/public-image-mirror/issues/2328 可以尝试其中别的方法
