### ISSUE TITLE
hipy

### ISSUE THREAD

**Issue by Hiram-Wong** [DaoCloud/public-image-mirror#16003]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 项目源码地址 或 组织地址

https://github.com/hjdhnx/hipy-server
https://github.com/hjdhnx/hipy-ui
https://github.com/hjdhnx/hipy-sniffer

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/hjdhnx/hipy-server/tree/master/hipy-all-docker

### 镜像仓库地址

https://hub.docker.com/r/hiramwong/hipy-sniffer
https://hub.docker.com/r/hiramwong/hipy-vue
https://hub.docker.com/r/hiramwong/hipy-fastapi

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 #2328 可以尝试其中别的方法
