### ISSUE TITLE
ollama

### ISSUE THREAD

**Issue by liuliuNLP** [DaoCloud/public-image-mirror#16107]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 项目源码地址 或 组织地址

https://github.com/ollama/ollama

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

官方docker地址

### 镜像仓库地址

https://hub.docker.com/r/ollama/ollama

**Comment by wzshiming** [comment]
已经在了
