### ISSUE TITLE
ghcr.io/immich-app

### ISSUE THREAD

**Issue by kidfruit** [DaoCloud/public-image-mirror#16345]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 项目源码地址 或 组织地址

ghcr.io/immich-app/**

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

### 镜像仓库地址

https://github.com/immich-app

**Comment by wzshiming** [comment]
已经在了
