### ISSUE TITLE
Collabora这个镜像的白名单，感谢大佬

### ISSUE THREAD

**Issue by peikunkun** [DaoCloud/public-image-mirror#16518]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/CollaboraOnline/online

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://hub.docker.com/r/collabora/code

### 镜像仓库地址

https://hub.docker.com/r/collabora/code

### 补充说明

内网在线文档编辑

**Comment by 17864219845** [comment]
同求
