### ISSUE TITLE
mattermost/focalboard不在白名单内

### ISSUE THREAD

**Issue by wushukui** [DaoCloud/public-image-mirror#16523]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

m.daocloud.io/docker.io/mattermost/focalboard

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

no

### 镜像仓库地址

mattermost/focalboard

**Comment by chuqiudada** [comment]
+1
