### ISSUE TITLE
docker.io/nezha123/titan-edge

### ISSUE THREAD

**Issue by YiMoWanXia** [DaoCloud/public-image-mirror#16522]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/Titannet-dao/titan-node

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://titannet.gitbook.io/titan-network-cn/hui-geng-si-ce-shi-wang/huygens-testnet/an-zhuang-cheng-xu-zhuan-qu/ming-ling-xing-an-zhuang#cong-yuan-dai-ma-gou-jian

### 镜像仓库地址

https://registry.hub.docker.com/r/nezha123/titan-edge

### 补充说明

1

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要求 https://github.com/DaoCloud/public-image-mirror/issues/2328 建议尝试其中别的方法
