### ISSUE TITLE
linuxserver/wps-office

### ISSUE THREAD

**Issue by cw45443943** [DaoCloud/public-image-mirror#16653]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/linuxserver/docker-wps-office

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/linuxserver/docker-wps-office/releases/tag/11.1.0.11719-ls62

### 镜像仓库地址

https://hub.docker.com/r/linuxserver/wps-office

**Comment by wzshiming** [comment]
已经有了
