### ISSUE TITLE
funcman/115pc

### ISSUE THREAD

**Issue by WYH-1229** [DaoCloud/public-image-mirror#16815]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/jlesage/docker-baseimage-gui

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

   docker pull funcman/115pc

### 镜像仓库地址

https://registry.hub.docker.com/r/funcman/115pc/

**Comment by wzshiming** [comment]
源码是 https://github.com/CALTyang/115pc-docker ,不符合要求
