### ISSUE TITLE
docker.io/acore

### ISSUE THREAD

**Issue by cinder1205** [DaoCloud/public-image-mirror#17024]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 项目源码地址 或 组织地址

docker.io/acore

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

docker.io/acore

### 镜像仓库地址

docker.io/acore

### 补充说明

docker.io/acore

**Comment by wzshiming** [comment]
这是什么项目, 没任何信息

**Comment by cinder1205** [comment]
一个开源的魔兽世界私人服务器搭建项目 ，官网是www.azerothcore.org。应该还需要其他的镜像，刚开始学docker，纯小白。
发自我的 iPhone

在 2024年7月1日，10:04，Shiming Zhang ***@***.***> 写道：

﻿

这是什么项目, 没任何信息
