### ISSUE TITLE
docker.io/datainpoint/xeus-cling-notebook:latest

### ISSUE THREAD

**Issue by baoyu-li** [DaoCloud/public-image-mirror#17115]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/jupyter-xeus/xeus-cling

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

docker.io/datainpoint/xeus-cling-notebook

### 镜像仓库地址

docker.io/datainpoint/xeus-cling-notebook

**Comment by wzshiming** [comment]
没找到 镜像和源码的关联
