### ISSUE TITLE
xprobe/xinference

### ISSUE THREAD

**Issue by anming81** [DaoCloud/public-image-mirror#17290]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/xorbitsai/inference

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

![image](https://github.com/DaoCloud/public-image-mirror/assets/66287586/3d406586-aed9-4513-a1c3-c8774941dec9)

### 镜像仓库地址

https://[hub.docker.com](https://hub.docker.com/u/xprobe)/u/xprobe/xinference

**Comment by wzshiming** [comment]
已经有了
