### ISSUE TITLE
hub.docker.com/layers/library/nginx:latest

### ISSUE THREAD

**Issue by moonlight-awaken** [DaoCloud/public-image-mirror#17312]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

hub.docker.com/layers/library/nginx:latest

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

hub.docker.com/layers/library/nginx:latest

### 镜像仓库地址

hub.docker.com/layers/library/nginx:latest

**Comment by wzshiming** [comment]
用m.daocloud.io/docker.io/library/nginx 拉就行了，你地址写错的

**Comment by moonlight-awaken** [comment]
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DaoCloud/public-image-mirror"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月1日(星期一) 中午11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DaoCloud/public-image-mirror] hub.docker.com/layers/library/nginx:latest (Issue #17312)





 
用m.daocloud.io/docker.io/library/nginx 拉就行了，你地址写错的
