### ISSUE TITLE
linyuan0213/nas-tools

### ISSUE THREAD

**Issue by pantou1991** [DaoCloud/public-image-mirror#17753]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/linyuan0213/nas-tools

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

github地址: [linyuan0213/nas-tools](https://github.com/linyuan0213/nas-tools)

### 镜像仓库地址

https://hub.docker.com/r/linyuan0213/nas-tools

**Comment by wzshiming** [comment]
这个镜像看起来不符合我们加入白名单的要求 https://github.com/DaoCloud/public-image-mirror/issues/2328
