### ISSUE TITLE
bash -c "$(curl -sSLf https://xy.ggbond.org/xy/docker_pull.sh)" -s emby/embyserver:latest

### ISSUE THREAD

**Issue by CinderellaGT** [DaoCloud/public-image-mirror#17792]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

bash -c "$(curl -sSLf https://xy.ggbond.org/xy/docker_pull.sh)"

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

bash -c "$(curl -sSLf https://xy.ggbond.org/xy/docker_pull.sh)" -s emby/embyserver:latest 

### 镜像仓库地址

bash -c "$(curl -sSLf https://xy.ggbond.org/xy/docker_pull.sh)" -s emby/embyserver:latest

**Comment by wzshiming** [comment]
docker.io/emby/embyserver 已经有了
