### ISSUE TITLE
docker pull jenkins/jenkins:2.466-jdk17

### ISSUE THREAD

**Issue by HeiZheJun** [DaoCloud/public-image-mirror#17890]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://www.jenkins.io/

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://www.jenkins.io/download/

### 镜像仓库地址

https://hub.docker.com/r/jenkins/jenkins

**Comment by wzshiming** [comment]
已经在了
