### ISSUE TITLE
docker.io/google/cadvisor/*

### ISSUE THREAD

**Issue by mturning** [DaoCloud/public-image-mirror#18246]
请求向白名单加入以下前缀

```
docker.io/google/cadvisor/*
```

_Originally posted by @JulyFinal in https://github.com/DaoCloud/public-image-mirror/issues/2328#issuecomment-2179704574_

**Comment by wzshiming** [comment]
按照模板填 https://github.com/DaoCloud/public-image-mirror/issues/new?assignees=&labels=allows+image&projects=&template=allows-image.yml
