### ISSUE TITLE
ACR Vector database: weaviate

### ISSUE THREAD

**Issue by lucasdengcn** [DaoCloud/public-image-mirror#18317]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

[semitechnologies/weaviate](https://github.com/weaviate/weaviate)

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://weaviate.io/developers/weaviate/installation/docker-compose

### 镜像仓库地址

https://cr.weaviate.io/semitechnologies/weaviate

### 补充说明

vector database for AI, RAG

**Comment by wzshiming** [comment]
已经有了
