### ISSUE TITLE
zulu-openjdk:17.0.10

### ISSUE THREAD

**Issue by lvgitt** [DaoCloud/public-image-mirror#18810]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&page_size=&name=17.0.1&ordering=

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&page_size=&name=17.0.1&ordering=

### 镜像仓库地址

docker pull azul/zulu-openjdk:17.0.10

**Comment by wzshiming** [comment]
不符合 #2328 要求, 没找到源码, 请完善之后再试
