### ISSUE TITLE
添加docker白名单：docker pull zlijingtao/neurobfuscator:latest

### ISSUE THREAD

**Issue by kid1214** [DaoCloud/public-image-mirror#18972]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/zlijingtao/Neurobfuscator

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

Pull Pre-build Docker Image
docker pull zlijingtao/neurobfuscator:lastest
docker tag zlijingtao/neurobfuscator:lastest neurob

### 镜像仓库地址

https://hub.docker.com/r/zlijingtao/neurobfuscator

**Comment by wzshiming** [comment]
不符合 #2328 要求, 能解释一下为什么要这个么

**Comment by kid1214** [comment]
> 不符合 #2328 要求, 能解释一下为什么要这个么

您好，我在从事模型安全方面的研究，并计划复现相关工作以验证和比较不同方法的效果。原项目[Neurobfuscator](https://github.com/zlijingtao/Neurobfuscator)是一个神经网络架构混淆工具，我需要访问Docker镜像中的环境来复现结果，贵项目提供的Docker镜像对于我的研究至关重要，感谢您考虑我的请求。

**Comment by wzshiming** [comment]
我看了下这个镜像挺大的 按照现在的限流规则估计 会卡几个小时
