### ISSUE TITLE
xiaoyaliu/glue不在白名单

### ISSUE THREAD

**Issue by lincheng77** [DaoCloud/public-image-mirror#19187]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://hub.docker.com/r/xiaoyaliu/glue

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://hub.docker.com/r/xiaoyaliu/glue

### 镜像仓库地址

https://hub.docker.com/r/xiaoyaliu/glue

**Comment by wzshiming** [comment]
看起来不符合 #2328 的要求, 没有源码, 没有明确的用途, 请补充后再提交
