### ISSUE TITLE
docker.io/collinwebdesigns/fastapi-dls:latest

### ISSUE THREAD

**Issue by ltm920716** [DaoCloud/public-image-mirror#19388]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://git.collinwebdesigns.de/oscar.krause/fastapi-dls

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

![image](https://github.com/DaoCloud/public-image-mirror/assets/12007227/5fddf1a2-7080-46ab-9984-20eb9abf4ba4)

### 镜像仓库地址

https://hub.docker.com/r/collinwebdesigns/fastapi-dls

**Comment by wzshiming** [comment]
看起来不符合 #2328  定义的要求
