### ISSUE TITLE
docker.io/jaaksi/sublinkx:latest

### ISSUE THREAD

**Issue by 465508617lai** [DaoCloud/public-image-mirror#19437]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://github.com/jaaksii/sublink

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/jaaksii/sublink

### 镜像仓库地址

https://hub.dockermirror.com/r/jaaksi/sublinkx

**Comment by wzshiming** [comment]
这个镜像不在计划支持之列, 可以参考 #2328  使用其他镜像源
