### ISSUE TITLE
请求添加以下仓库的所有镜像到白名单中以供其他小伙伴学习使用

### ISSUE THREAD

**Issue by Trust22-marker** [DaoCloud/public-image-mirror#19823]
### 白名单级别

需要这个镜像仓库下所有镜像 (如 registry.k8s.io/**)

### 项目源码地址 或 组织地址

https://github.com/micyo202/lion

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

源码中以下五个项目构成了镜像并推送到了Docker Hub上，并且后期会根据项目的优化产生新版本的镜像：
lion-admin
lion-auth
lion-common
lion-demo
lion-gateway

### 镜像仓库地址

https://hub.docker.com/u/micyo202

**Comment by wzshiming** [comment]
这个项目看起来不符合加入的要求呢, 可以参考上面的要求, 或使用其中提供的其他镜像源 #2328
