### ISSUE TITLE
两个镜像

### ISSUE THREAD

**Issue by leocockroach** [DaoCloud/public-image-mirror#19846]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 项目源码地址 或 组织地址

https://hub.docker.com/r/temporalio/auto-setup
https://hub.docker.com/r/kbudde/rabbitmq-exporter

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://hub.docker.com/r/temporalio/auto-setup
https://hub.docker.com/r/kbudde/rabbitmq-exporter

### 镜像仓库地址

https://hub.docker.com/r/temporalio/auto-setup
https://hub.docker.com/r/kbudde/rabbitmq-exporter

**Comment by wzshiming** [comment]
没有找到项目对应的源码呢 请按照模板要求补完信息 #2328
