### ISSUE TITLE
xiaoya

### ISSUE THREAD

**Issue by kokojacket** [DaoCloud/public-image-mirror#19976]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 项目源码地址 或 组织地址

https://github.com/monlor/docker-xiaoya

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/monlor/docker-xiaoya/blob/main/docker-compose-all.yml

### 镜像仓库地址

ghcr.io/monlor/xiaoya-jellyfin:latest
ghcr.io/monlor/xiaoya-alist:latest
ghcr.io/monlor/xiaoya-metadata:latest
ghcr.io/monlor/xiaoya-embyserver:latest

**Comment by wzshiming** [comment]
这个镜像不符合加入白名单的要求 建议使用 #2328 里其他的镜像源
