### ISSUE TITLE
需要同步宝塔镜像，请通过一下

### ISSUE THREAD

**Issue by lcahdb** [DaoCloud/public-image-mirror#20083]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/pch18/baota

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 补充说明

以前的宝塔地址全部失效了，所以需要重新生成

**Comment by wzshiming** [comment]
这个镜像不符合加入白名单的要求#2328 没有源码

**Comment by wzshiming** [comment]
你可以使用#2328里的其他镜像源

**Comment by wzshiming** [comment]
这个镜像不符合加入白名单的要求 建议使用 #2328 里其他的镜像源
