### ISSUE TITLE
docker.io/xiaoyaliu/glue:latest

### ISSUE THREAD

**Issue by zzhzzh1007** [DaoCloud/public-image-mirror#20129]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/xiaoyaliu/glue:latest

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
建议使用 #2328 里其他的镜像源
