### ISSUE TITLE
添加白名单

### ISSUE THREAD

**Issue by chichibuduixian8701** [DaoCloud/public-image-mirror#20234]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

akimio/autofilm

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://github.com/Akimio521/AutoFilm

**Comment by wzshiming** [comment]
看起来不符合加入白名单的要求建议使用 #2328 里其他镜像源
