### ISSUE TITLE
bloodstar/hexo

### ISSUE THREAD

**Issue by easygoal** [DaoCloud/public-image-mirror#20257]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

[bloodstar/hexo](https://github.com/appotry/docker-hexo)

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://github.com/appotry/docker-hexo

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/appotry/docker-hexo

### 补充说明

https://github.com/appotry/docker-hexo

**Comment by wzshiming** [comment]
看起来不符合加入白名单的要求建议使用 #2328 里其他镜像源
