### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by flipped11** [DaoCloud/public-image-mirror#20461]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/mzzsfy/auto-proxy-pool

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

**Comment by wzshiming** [comment]
看起来不符合加入白名单的要求建议使用 #2328 里其他镜像源
