### ISSUE TITLE
docker.io/xiaoyaliu/glue:latest

### ISSUE THREAD

**Issue by V-Bean** [DaoCloud/public-image-mirror#20553]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/xiaoyaliu/glue:latest

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://xn--tkrq60cewc.top/xiaoyaembyssh/

### 补充说明

跟着教程折腾过程中发现一键安装emby时从ssh代码行中发现无法从docker.io拉取docker.io/xiaoyaliu/glue:latest，且该镜像不在白名单中，因此尝试申请添加，前一步安装xiaoya-alist时也是走的大佬您的镜像库才能拉取的

**Comment by wzshiming** [comment]
看起来不符合加入白名单的要求建议使用 #2328 里其他镜像源
