### ISSUE TITLE
hanhongyong/ms365-e5-renew-x

### ISSUE THREAD

**Issue by mogudunji** [DaoCloud/public-image-mirror#20668]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

hanhongyong/ms365-e5-renew-x

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
这个不符合我们加入白名单的要求, 可以使用这里的其他镜像源 #2328
