### ISSUE TITLE
pi-node-docker

### ISSUE THREAD

**Issue by hgqhgq520** [DaoCloud/public-image-mirror#20758]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

docker.io/pinetwork/pi-node-docker
docker.io/ese7en/node-port-test

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

### 项目源码地址 或 组织地址

https://github.com/PiCoreTeam/pi-node-docker

**Comment by wzshiming** [comment]
这个镜像不符合我们加入白名单的要 可以使用 #2328 里其他的镜像源
