### ISSUE TITLE
我需要添加镜像白名单，谢谢！

### ISSUE THREAD

**Issue by lzf54213** [DaoCloud/public-image-mirror#20940]
### 白名单级别

需要这个镜像仓库下所有镜像 (如 registry.k8s.io/**)

### 镜像仓库地址

docker.io
{
  "registry-mirrors": [
    "https://dockerhub.icu",
    "https://docker.chenby.cn",
    "https://docker.1panel.live",
    "https://docker.awsl9527.cn",
    "https://docker.anyhub.us.kg",
    "https://dhub.kubesre.xyz"
  ]
}

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
建议使用 #2328 其他镜像源
