### ISSUE TITLE
docker.io/library/postgres:15.2

### ISSUE THREAD

**Issue by liduopie** [DaoCloud/public-image-mirror#20947]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/_/postgres

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://www.postgresql.org/

**Comment by wzshiming** [comment]
已经在白名单了
