### ISSUE TITLE
docker.io/adolfintel/speedtest:latest

### ISSUE THREAD

**Issue by Rio-UI** [DaoCloud/public-image-mirror#20944]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/adolfintel/speedtest

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

**Comment by wzshiming** [comment]
没找到源码, 建议使用 #2328 其他镜像源
