### ISSUE TITLE
docker pull homeassistant/home-assistant:dev

### ISSUE THREAD

**Issue by nidexiaobai** [DaoCloud/public-image-mirror#21320]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker pull homeassistant/home-assistant:dev

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

**Comment by wzshiming** [comment]
已经在了
