### ISSUE TITLE
m.daocloud.io/docker.io/xiaoyaliu/emby:latest

### ISSUE THREAD

**Issue by Alexzhang04** [DaoCloud/public-image-mirror#21358]
### 白名单级别

需要这个镜像仓库下所有镜像 (如 registry.k8s.io/**)

### 镜像仓库地址

m.daocloud.io/docker.io/xiaoyaliu/emby:latest

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

docker.io/xiaoyaliu/emby:latest

**Comment by wzshiming** [comment]
看起来没有相关信息, 推荐使用 #2328 里其他镜像源
