### ISSUE TITLE
xiaoyaliu/alist,haroldli/xiaoya-tvbox

### ISSUE THREAD

**Issue by 43119601** [DaoCloud/public-image-mirror#21425]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

docker.io/xiaoyaliu/alist,haroldli/xiaoya-tvbox

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
看起来没有相关信息呢, 推荐使用 #2328 里其他镜像源
