### ISSUE TITLE
docker.io/moelin/1panel:latest

### ISSUE THREAD

**Issue by ohuu00** [DaoCloud/public-image-mirror#21433]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://docker.io/moelin/1panel:latest

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
看起来不是官方认证的镜像并且没有相关信息呢, 推荐使用 #2328 里其他镜像源
