### ISSUE TITLE
docker.m.daocloud.io/haishanh/yacd不在白名单

### ISSUE THREAD

**Issue by wushukui** [DaoCloud/public-image-mirror#21492]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.m.daocloud.io/haishanh/yacd

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

docker.m.daocloud.io/haishanh/yacd

**Comment by wzshiming** [comment]
看起来没有相关信息呢, 推荐使用 #2328 里其他镜像源
