### ISSUE TITLE
申请添加docker.io/tensorchord/pgvecto-rs到白名单

### ISSUE THREAD

**Issue by kozmers** [DaoCloud/public-image-mirror#21525]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

pgvecto.rs

**Comment by wzshiming** [comment]
已经有了
