### ISSUE TITLE
docker.io/zishuo/embyserver:latest

### ISSUE THREAD

**Issue by bolis1982** [DaoCloud/public-image-mirror#21560]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/zishuo/embyserver/

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

**Comment by wzshiming** [comment]
看起来没有相关信息呢, 推荐使用 #2328 里其他镜像源
