### ISSUE TITLE
metagpt

### ISSUE THREAD

**Issue by jikerom** [DaoCloud/public-image-mirror#21991]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/metagpt/metagpt

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
这不是镜像仓库官方认证过的也没信息, 推荐使用 #2328 里其他镜像源
