### ISSUE TITLE
Not all tags being sync ? if so, should we document it ?

### ISSUE THREAD

**Issue by panpan0000** [DaoCloud/public-image-mirror#220]
for example. `minio/minio:RELEASE.2022-07-29T19-40-48Z` is not sync.
If it's expected behavior, I guess some regular expression filter it out ? (maybe only sync those tags with vx.y.z ?) 
if so ,please write this NOTES down in documents to avoid confusion.

```
# docker pull docker.m.daocloud.io/minio/minio:RELEASE.2022-07-29T19-40-48Z
Error response from daemon: manifest for docker.m.daocloud.io/minio/minio:RELEASE.2022-07-29T19-40-48Z not found: manifest unknown: manifest unknown
```

**Comment by wzshiming** [comment]
tag 不在同步列表
这个问题后续支持 懒加速 修复
