### ISSUE TITLE
加入白名单

### ISSUE THREAD

**Issue by cdataishuaile** [DaoCloud/public-image-mirror#22032]
### 白名单级别

需要这个镜像仓库下所有镜像 (如 registry.k8s.io/**)

### 镜像仓库地址

https://docker.m.daocloud.io/v2/mendix/

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

源码无法提供 mendix是低代码 代码块开发方式

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

这部分是sh脚本中写的镜像源

### 补充说明

您好
![image](https://github.com/user-attachments/assets/1086e695-3d99-4691-a197-f96b93a41d96)
我这边是用mendix进行项目开发和部署的 之前一直是使用您提供的渠道进行 镜像下载的  然后我们服务器的项目迁移了 这些镜像需要在新的服务器上重新下载，很急，请您将我加入白名单

**Comment by wzshiming** [comment]
没有源码不符合加入白名单的要求, 推荐使用 https://github.com/DaoCloud/public-image-mirror/issues/2328 里其他镜像源
