### ISSUE TITLE
增减Open WebUI (Formerly Ollama WebUI) 白名单

### ISSUE THREAD

**Issue by RJustice** [DaoCloud/public-image-mirror#22174]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

ghcr.io/open-webui/open-webui

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://github.com/open-webui/open-webui

**Comment by wzshiming** [comment]
已经在白名单了
