### ISSUE TITLE
cloudtogouser/pageplug-ce

### ISSUE THREAD

**Issue by chenarmy** [DaoCloud/public-image-mirror#22184]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

cloudtogouser/pageplug-ce

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
不符合加入白名单的要求 #2328 可以使用其他镜像源
