### ISSUE TITLE
docker.io/atmoz/sftp:latest

### ISSUE THREAD

**Issue by liu280790081** [DaoCloud/public-image-mirror#22536]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

https://github.com/DaoCloud/public-image-mirror/issues/18410

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
