### ISSUE TITLE
docker.io/xuxueli/xxl-job-admin:2.4.1

### ISSUE THREAD

**Issue by deanjoson** [DaoCloud/public-image-mirror#22571]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/xuxueli/xxl-job-admin

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://www.xuxueli.com/

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
