### ISSUE TITLE
添加jfrog仓库

### ISSUE THREAD

**Issue by qw1212** [DaoCloud/public-image-mirror#22577]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

docker.bintray.io/jfrog/artifactory-cpp-ce

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
