### ISSUE TITLE
镜像不在白名单什么意思？

### ISSUE THREAD

**Issue by xclidongbo** [DaoCloud/public-image-mirror#22718]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

111

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

111

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

111

### 补充说明

Failed to pull image "jc21/nginx-proxy-manager:2.11.3": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/jc21/nginx-proxy-manager:2.11.3": failed to copy: httpReadSeeker: failed open: unexpected status code https://docker.m.daocloud.io/v2/jc21/nginx-proxy-manager/blobs/sha256:28147ecda6596be570548a7f81be5bc8eb487a3e3a7d6dca8595b612db1a92d5?ns=docker.io: 403 Forbidden - Server message: denied: 🚫 这镜像不在白名单. this image is not in the allowlist. 📦 https://github.com/DaoCloud/public-image-mirror/issues/2328

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
