### ISSUE TITLE
docker.io/jc21/nginx-proxy-manager:2.11.3 添加白名单

### ISSUE THREAD

**Issue by xclidongbo** [DaoCloud/public-image-mirror#22719]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/jc21/nginx-proxy-manager:2.11.3

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

### 项目源码地址 或 组织地址

docker.io/jc21/nginx-proxy-manager:2.11.3

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

docker.io/jc21/nginx-proxy-manager:2.11.3

### 补充说明

docker.io/jc21/nginx-proxy-manager:2.11.3

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
