### ISSUE TITLE
请求添加confluentinc相关镜像

### ISSUE THREAD

**Issue by yyag256** [DaoCloud/public-image-mirror#22721]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

https://hub.docker.com/r/confluentinc/cp-kafka

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

### 补充说明

这个官方认可的kafka库，还有命令docker pull docker.m.daocloud.io/bitnami/kafka，无法拉取

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
