### ISSUE TITLE
teslamate/grafana

### ISSUE THREAD

**Issue by 97337** [DaoCloud/public-image-mirror#22723]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/teslamate/grafana/tags

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
看起来没补充要求的相关信息 推荐使用 #2328 中其他镜像源
