### ISSUE TITLE
新增Hive数仓为白名单

### ISSUE THREAD

**Issue by elkan1788** [DaoCloud/public-image-mirror#22737]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

https://[hub.docker.com/r/apache/hive](https://hub.docker.com/r/apache/hive)

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

### 项目源码地址 或 组织地址

https://github.com/apache/hive

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

在官方首页：https://hive.apache.org/ 有添加Docker镜像地址下载按钮

**Comment by wzshiming** [comment]
已经在白名单了

**Comment by elkan1788** [comment]
嗯嗯，之前也发现了，使用是快速开始中的前缀域名：m.daocloud.io/docker.io/library/， 遇到了白名单问题，现在解决了，谢谢。
