### ISSUE TITLE
docker.io/tinyserve/xteve:latest

### ISSUE THREAD

**Issue by sbfcudx** [DaoCloud/public-image-mirror#22745]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/tinyserve/xteve:latest

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

### 项目源码地址 或 组织地址

https://docker.io

**Comment by wzshiming** [comment]
看起来没没有补充相关信息, 推荐使用 #2328 里其他镜像源
