### ISSUE TITLE
docker pull screego/server:1

### ISSUE THREAD

**Issue by master-zh** [DaoCloud/public-image-mirror#23093]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/screego/server/tags

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
看起来不是官方认证的镜像 推荐使用 #2328  中其他的镜像源
