### ISSUE TITLE
申请镜像：docker.io/mobz/elasticsearch-head:5

### ISSUE THREAD

**Issue by Freudia01** [DaoCloud/public-image-mirror#23155]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/mobz/elasticsearch-head:5

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 补充说明

或者您能提供我其他仓库的elasticsearch-head也可以
镜像介绍：
Elasticsearch-Head 是一个基于浏览器的开源工具，用于可视化和管理 Elasticsearch 集群。它提供了一个直观的用户界面，可以帮助用户轻松地监控和管理 Elasticsearch 集群中的索引、节点、分片等。

**Comment by wzshiming** [comment]
没看到对应的源码, 推荐使用 #2328 中其他镜像源

**Comment by Freudia01** [comment]
用了你推荐的好使了，谢谢！
