### ISSUE TITLE
申请镜像英伟达GPU Operator的镜像

### ISSUE THREAD

**Issue by pycjava** [DaoCloud/public-image-mirror#23175]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

nvcr.io/nvidia/cloud-native
nvcr.io/nvidia
nvcr.io/nvidia/k8s

### 这是镜像仓库官方认证过的么?

是的 (不需要填下面的信息)

**Comment by wzshiming** [comment]
已经在白名单了
