### ISSUE TITLE
moviepilot

### ISSUE THREAD

**Issue by willzhuce** [DaoCloud/public-image-mirror#23188]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/jxxghp/moviepilot

### 这是镜像仓库官方认证过的么?

不是 (请补充下面的信息, 乱填将关闭申请)

### 项目源码地址 或 组织地址

https://github.com/jxxghp/MoviePilot

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://wiki.movie-pilot.org/zh/install

**Comment by wzshiming** [comment]
已经在白名单了
