### ISSUE TITLE
gdy666/lucky

### ISSUE THREAD

**Issue by admin-tec** [DaoCloud/public-image-mirror#23458]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/?_gl=1*1l6wkn7*_gcl_au*MTY4NzM5MDM1MS4xNzIyNTYyODkx*_ga*OTI4NzU5MzEyLjE3MjI1NjI4OTE.*_ga_XJWPQMJYHQ*MTcyMjU2Mjg5MC4xLjEuMTcyMjU2MzQ3Ny42MC4wLjA.

### 这是镜像仓库官方认证过的么?

是的 - **镜像仓库**认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 不需要填下面的信息

**Comment by wzshiming** [comment]
不要乱填
