### ISSUE TITLE
添加白名单

### ISSUE THREAD

**Issue by zhanyigo** [DaoCloud/public-image-mirror#23461]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/**)

### 镜像仓库地址

gcr.io/kubebuilder/**

### 这是镜像仓库官方认证过的么?

不是 - 请补充下面的信息

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/open-telemetry/opentelemetry-collector 项目用到 gcr.io/kubebuilder/kube-rbac-proxy

**Comment by wzshiming** [comment]
已经有了
