### ISSUE TITLE
是geoserver镜像

### ISSUE THREAD

**Issue by PengchengI8** [DaoCloud/public-image-mirror#23553]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hubgw.docker.com/r/kartoza/geoserver

### 这是镜像仓库官方认证过的么?

是的 - **镜像仓库**认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 不需要填下面的信息

**Comment by wzshiming** [comment]
不是认证过的镜像 #2328 推荐使用其中其他镜像源
