### ISSUE TITLE
docker.io/agentdvr/agentdvr:latest

### ISSUE THREAD

**Issue by liuqi2978** [DaoCloud/public-image-mirror#23733]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com

### 这是镜像仓库官方认证过的么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/

**Comment by wzshiming** [comment]
不符合 #2328 里要求推荐使用其中其他镜像源
