### ISSUE TITLE
能否修改一下  限流政策？

### ISSUE THREAD

**Issue by 8502596** [DaoCloud/public-image-mirror#23752]
如题  新手不会操作  只是按教程  安装 rancher   添加本地集群   就  429 Too Many Requests   之后就不会了  只能等着 看他什么时候正常

**Comment by yankay** [comment]
HI @8502596 

目前流量很大，本站全息用爱发电。限流策略也是不得已。
如果想更顺畅使用，可以自己搭建 ss 代理等方式。
