### ISSUE TITLE
pbogre/jetlog:latest

### ISSUE THREAD

**Issue by xfwanglxf** [DaoCloud/public-image-mirror#23853]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://registry.hub.docker.com/r/pbogre/jetlog/

### 这是镜像仓库官方认证过的么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
不符合 #2328 要求推荐使用其他其他镜像源
