### ISSUE TITLE
请求添加ingress镜像到白名单

### ISSUE THREAD

**Issue by LIANGQI0811** [DaoCloud/public-image-mirror#23885]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://registry.k8s.io/ingress-nginx/controller:v1.10.1@sha256:e24f39d3eed6bcc239a56f20098878845f62baa34b9f2be2fd2c38ce9fb0f29e

### 这是镜像仓库官方认证过的么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
已经在白名单了
