### ISSUE TITLE
添加一个镜像

### ISSUE THREAD

**Issue by reed-fea** [DaoCloud/public-image-mirror#23954]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/xuxueli/xxl-job-admin

### 这是镜像仓库官方认证过的么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://www.xuxueli.com/xxl-job/

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://www.xuxueli.com/xxl-job/#%E5%85%B6%E4%BB%96%EF%BC%9ADocker%20%E9%95%9C%E5%83%8F%E6%96%B9%E5%BC%8F%E6%90%AD%E5%BB%BA%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83%EF%BC%9A

### 补充说明

xxl-job 是一个使用 java 编写的 任务调度程序

**Comment by wzshiming** [comment]
已经有了
