### ISSUE TITLE
docker.io/xhofe/alist

### ISSUE THREAD

**Issue by DreamcatcherGJ** [DaoCloud/public-image-mirror#23972]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/xhofe/alist

### 这是镜像仓库官方认证过的么?

是的 - **镜像仓库**认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 不需要填下面的信息

### 项目源码地址 或 组织地址

https://github.com/alist-org/alist

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://alist.nn.ci/

**Comment by wzshiming** [comment]
已经有了
