### ISSUE TITLE
registry.k8s.io/etcd:3.5.11-0

### ISSUE THREAD

**Issue by sunzm4work** [DaoCloud/public-image-mirror#2425]

**Comment by wzshiming** [comment]
同步方法参考 https://github.com/DaoCloud/public-image-mirror?tab=readme-ov-file#%E5%8D%95%E6%AC%A1%E5%8D%95%E9%95%9C%E5%83%8F%E5%90%8C%E6%AD%A5

**Comment by wzshiming** [comment]
参考 #2430 主动同步
