### ISSUE TITLE
lmscommunity/logitechmediaserver:latest

### ISSUE THREAD

**Issue by huangshiahi** [DaoCloud/public-image-mirror#24351]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/lmscommunity/logitechmediaserver

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
没有附带相关信息 推荐使用 #2328 里其他镜像源
