### ISSUE TITLE
maildev/maildev

### ISSUE THREAD

**Issue by ehyman** [DaoCloud/public-image-mirror#24399]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/maildev/maildev

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://hub.docker.com/r/maildev/maildev

**Comment by wzshiming** [comment]
不是被认证的也没有附带相关信息 推荐使用 #2328 里其他镜像源
