### ISSUE TITLE
 wxedge.mirror.aliyuncs.com/onething1/wxedge:latest

### ISSUE THREAD

**Issue by Mike0510** [DaoCloud/public-image-mirror#24567]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

 wxedge.mirror.aliyuncs.com/onething1/

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
这个不需要加速
