### ISSUE TITLE
垂询大流量相关事宜

### ISSUE THREAD

**Issue by Lakr233** [DaoCloud/public-image-mirror#2464]
朋友推荐使用这个服务同步 ghcr.io/cirruslabs/macos-sonoma-xcode:latest 这个仓库

- 这个 container image 大概是 54.8 GB compressed 的大小
- 预计消耗每个月一次到两次 pull （个人）

看到 readme 写到大流量和 ip 会屏蔽 想问一下怎么样算大流量 还是说这个就算大流量了

**Comment by wzshiming** [comment]
这个还好吧, 之前是 10 天被刷了 70 T

**Comment by Lakr233** [comment]
收到

**Comment by wzshiming** [comment]
这种比较大的还是实际拉的时候 发起一次主动同步吧 https://github.com/DaoCloud/public-image-mirror?tab=readme-ov-file#%E5%8D%95%E6%AC%A1%E5%8D%95%E9%95%9C%E5%83%8F%E5%90%8C%E6%AD%A5
