### ISSUE TITLE
docker.io/rocketchat/rocket.chat:latest

### ISSUE THREAD

**Issue by avre99** [DaoCloud/public-image-mirror#24670]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/rocketchat/rocket.chat

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/RocketChat/Rocket.Chat

**Comment by wzshiming** [comment]
已经存在了 
https://hub.docker.com/_/rocket.chat
