### ISSUE TITLE
screego/server镜像

### ISSUE THREAD

**Issue by xingqijiu123** [DaoCloud/public-image-mirror#24819]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

https://hub.docker.com/r/screego/server

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
没有相关信息 推荐使用 #2328 里其他镜像源
