### ISSUE TITLE
docker.io/garethflowers/svn-server:latest

### ISSUE THREAD

**Issue by LuckyPDX** [DaoCloud/public-image-mirror#24891]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/garethflowers/svn-server

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
没有相关信息 推荐使用 #2328 里其他镜像源
