### ISSUE TITLE
是否能增加mcr镜像加速地址

### ISSUE THREAD

**Issue by yirenkeji555** [DaoCloud/public-image-mirror#25]
ARG VARIANT=11-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/java:0-${VARIANT}
![image](https://user-images.githubusercontent.com/48214423/146171627-30bb35df-88be-419b-b27d-72fb20a8f4df.png)
![image](https://user-images.githubusercontent.com/48214423/146171650-5792533c-d98f-4c3b-837f-06e7d0302f10.png)

**Comment by wzshiming** [comment]
@yank1 加个 mcr.microsoft.com 源么
