### ISSUE TITLE
pgadmin4 镜像白名单申请

### ISSUE THREAD

**Issue by iceopen** [DaoCloud/public-image-mirror#25124]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

https://hub.docker.com/r/dpage/pgadmin4/

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html

### 补充说明

pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world.

**Comment by wzshiming** [comment]
已经在白名单了
