### ISSUE TITLE
influxdb

### ISSUE THREAD

**Issue by ganting** [DaoCloud/public-image-mirror#25132]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/layers/library/influxdb/1.8.10/images/sha256-a1cff51e969116db95524c76492de787f478df0c0b18e71377aa4907b7f671e1?context=explore

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
已经在了
