### ISSUE TITLE
docker.io/yiisoftware/yii2-php

### ISSUE THREAD

**Issue by xuweiguo** [DaoCloud/public-image-mirror#25719]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

docker.io/yiisoftware/yii2-php

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
没有相关信息 推荐使用 #2328 里其他镜像源

**Comment by xuweiguo** [comment]
![image](https://github.com/user-attachments/assets/b911fca3-27d5-4167-812e-6629d47c2cdb)
这个是php的YII框架官方镜像仓库

**Comment by xuweiguo** [comment]
> 没有相关信息 推荐使用 #2328 里其他镜像源

这个是php的YII框架官方镜像仓库
