### ISSUE TITLE
 请求把jellyfin加入白名单

### ISSUE THREAD

**Issue by insane4tay** [DaoCloud/public-image-mirror#25763]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.con/r/jellyfin/jellyfin

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

### 补充说明

这是一个开源媒体服务器，我已经同步到仓库，但是发现没在白名单，希望能够加入白名单，多谢

**Comment by insane4tay** [comment]
镜像地址 docker.io/r/jellyfin/jellyfin

**Comment by wzshiming** [comment]
已经有了
