### ISSUE TITLE
请求添加docker.io/chainguard/cadvisor 镜像至白名单

### ISSUE THREAD

**Issue by LBBX11** [DaoCloud/public-image-mirror#26234]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/chainguard/cadvisor:latest

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
看起来没填相关信息, 推荐使用#2328里其他镜像源
