### ISSUE TITLE
docker.io/zixia/wechat:latest

### ISSUE THREAD

**Issue by taiyang333** [DaoCloud/public-image-mirror#26237]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://registry.hub.docker.com/r/zixia/wechat

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://registry.hub.docker.com/r/zixia/wechat

**Comment by taiyang333** [comment]
https://raw.githubusercontent.com/huan/docker-wechat/master/dochat.sh

**Comment by wzshiming** [comment]
看起来没填相关信息, 推荐使用#2328里其他镜像源
