### ISSUE TITLE
docker.io/opengatecollaboration/gate:latest

### ISSUE THREAD

**Issue by xiaochaorouz** [DaoCloud/public-image-mirror#26661]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/opengatecollaboration/gate:latest

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
这不是被镜像仓库认证的 并且没填信息 推荐使用 #2328 里其他镜像源
