### ISSUE TITLE
docker.io/pinetwork/pi-node-docker:latest

### ISSUE THREAD

**Issue by a7828254** [DaoCloud/public-image-mirror#26757]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://github.com/DaoCloud/public-image-mirror/issues/11967

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

1

### 补充说明

1

**Comment by wzshiming** [comment]
这不是被镜像仓库认证的 并且没填信息 推荐使用 #2328 里其他镜像源
