### ISSUE TITLE
infiniflow/infinity:nightly

### ISSUE THREAD

**Issue by Tinystormjojo** [DaoCloud/public-image-mirror#26898]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/infiniflow/infinity:nightly

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
不是受认证的镜像也没有提供要求的信息, 推荐使用 #2328 里其它源
