### ISSUE TITLE
adtiming/omjava:latest

### ISSUE THREAD

**Issue by wanghy8166** [DaoCloud/public-image-mirror#28011]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/adtiming/omjava:latest

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://www.adtiming.com/

**Comment by wzshiming** [comment]
不是受镜像仓库验证的镜像, 也没有提供对应的资料, 没有源码, 推荐使用 #2328 里其他镜像源
