### ISSUE TITLE
excalidraw

### ISSUE THREAD

**Issue by Zhouyqcat** [DaoCloud/public-image-mirror#28171]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://docker.io/excalidraw/excalidraw

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://docker.io/excalidraw/excalidraw

**Comment by wzshiming** [comment]
这个镜像不是受到镜像仓库认证的也没提供要求的信息, 推荐使用 #2328 里推荐的其他镜像源
