### ISSUE TITLE
请求加白docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4

### ISSUE THREAD

**Issue by tanganyu1114** [DaoCloud/public-image-mirror#28195]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
这个镜像不是受到镜像仓库认证的也没提供要求的信息, 推荐使用 #2328 里推荐的其他镜像源
