### ISSUE TITLE
需要registry.k8s.io/ingress-nginx/kube-webhook-certgen

### ISSUE THREAD

**Issue by zehonghuang** [DaoCloud/public-image-mirror#28208]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.0@sha256:44d1d0e9f19c63f58b380c5fddaca7cf22c7cee564adeff365225a5df5ef3334

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
registry.k8s.io 已经在白名单
