### ISSUE TITLE
clash

### ISSUE THREAD

**Issue by chq11** [DaoCloud/public-image-mirror#29094]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/dreamacro/clash

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
这个镜像不是受认证的, 也没提供要求的信息
所以本次不予支持加入白名单

推荐使用 #2328 里其他源
或者可以尝试直连
