### ISSUE TITLE
docker.io/windoge/maa-control-api:latest

### ISSUE THREAD

**Issue by cj0928** [DaoCloud/public-image-mirror#29150]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/windoge/maa-control-api/tags

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/gxy12345/maa_control_api?tab=readme-ov-file

**Comment by wzshiming** [comment]
这个镜像不是受认证的
所以本次不予支持加入白名单

推荐使用 #2328 里其他源
或者可以尝试直连
