### ISSUE TITLE
happynet

### ISSUE THREAD

**Issue by happyntec** [DaoCloud/public-image-mirror#29344]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

docker.io/happyn/happynet:latest

docker.io/happyn/supernode:latest

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/happynclient/happynlinux

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/happynclient/happynlinux

### 补充说明

您好，这是本人开发的一个开源的组网软件，希望能够收录

**Comment by wzshiming** [comment]
这个镜像不是受认证的, 也没提供要求的信息
所以本次不予支持加入白名单, 请补全后再试

推荐使用 #2328 里其他源
或者可以尝试直连
