### ISSUE TITLE
wxhere/bitcomet:latest

### ISSUE THREAD

**Issue by 1665169869** [DaoCloud/public-image-mirror#29602]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/wxhere/bitcomet

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

http://wiki-zh.bitcomet.com/linux%E7%89%88bitcomet%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

http://wiki-zh.bitcomet.com/linux%E7%89%88bitcomet%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97

### 补充说明

请求添加bitcomet docker镜像

**Comment by wzshiming** [comment]
这个镜像不是受认证的, 也没提供要求的信息
所以本次不予支持加入白名单, 请补全后再试

推荐使用 #2328 里其他源
或者可以尝试直连
