### ISSUE TITLE
mlikiowa/napcat-docker:latest 请求添加白名单

### ISSUE THREAD

**Issue by 1665169869** [DaoCloud/public-image-mirror#29806]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

[https://hub.docker.com/r/mlikiowa/napcat-docker](https://hub.docker.com/r/mlikiowa/napcat-docker)

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

[https://github.com/NapNeko/NapCat-Docker](https://github.com/NapNeko/NapCat-Docker)
[https://github.com/NapNeko/NapCatQQ](https://github.com/NapNeko/NapCatQQ)

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

[https://napneko.github.io/zh-CN/guide/getting-started](https://napneko.github.io/zh-CN/guide/getting-started)
官方文档中，提及到此镜像，并且根据作者github主页：[NapKeko](https://github.com/NapNeko)可以看到两个项目分别为[NapCatQQ](https://github.com/NapNeko/NapCatQQ)和[NapCat-Docker](https://github.com/NapNeko/NapCat-Docker)都是他的
![image](https://github.com/user-attachments/assets/2ab4945c-78ec-4c4f-9690-a8e0c1905690)

**Comment by wzshiming** [comment]
本次不予支持加入白名单可能有以下原因

- 这个镜像不是受认证的, 也没提供要求的信息
- 只有构建产物没有源码的
- 不是正经的开源项目
- 项目 ⭐️ 过低的
- 仅为国内用户服务的镜像 (绕一圈没必要)
- 涉及魔法/科学, 盗版等...

请补全后再试 或者 推荐尝试 #2328 里其他源
