### ISSUE TITLE
docker.io/1panel/maxkb:v1.5.1

### ISSUE THREAD

**Issue by liningbo2017** [DaoCloud/public-image-mirror#30104]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/layers/1panel/maxkb/v1.5.1/images/sha256-1aad3c33cfddb40e97b4821a3bf8d32cd39f0e5c51096031775394683ba547dc?context=explore

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
已经在白名单了
