### ISSUE TITLE
添加 TriliumNotes 相关镜像

### ISSUE THREAD

**Issue by dousha** [DaoCloud/public-image-mirror#30683]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/triliumnext/notes

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/TriliumNext/Notes

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/TriliumNext/Notes/blob/develop/docker-compose.yml
https://triliumnext.github.io/Docs/Wiki/docker-server-installation.html

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
