### ISSUE TITLE
docker.io/library/apache/zeppelin:0.11.2

### ISSUE THREAD

**Issue by gengyuntuo** [DaoCloud/public-image-mirror#30685]
IMAGE SYNC

**Comment by gengyuntuo** [comment]
docker.io/library/apache/zeppelin:0.11.2

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
