### ISSUE TITLE
docker.io/blllicn/ptools:latest

### ISSUE THREAD

**Issue by 1379720295** [DaoCloud/public-image-mirror#31201]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/blllicn/ptools:latest

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

### 补充说明

pt相关的。<html><body>

  | 本系统只适用于群辉系统。 进入群辉系统安装docker，如果已安装docker可以略过此步骤。选择套件，设置套件来源，添加https://packages.synocommunity.com  进入套件后，搜索docker ，选择安装。  安装docker后，进入docker，注册表搜索ptools ，会出现blllicn/ptools，选择最新版安装，目前是v0.3版本。  docker里点击映像，选择blllicn/ptools安装。 安装后，进入容器界面，点击blllicn/ptools选择编辑，如下设置  其中media是媒体库文件夹位置，就是选择需要做种的文件夹的位置。/log是日志，/db是数据库，这两个文件自己随意建立个文件夹就可以。 注意，装载路径请按照图上的输入，不要更换装载路径，文件夹选择可以根据自己实际选择。  其他设置不变，点击应用后选择启动。 输入nas IP地址加8000端口，即可进入发种鸡界面，默认用户名和密码是admin。 点击seeder，增加task  安装要求，填写标题名称，制作组后缀，豆瓣和imdb链接，种子类型按照实际填写，分季和合集按照实际填写。  file paths 选择做种的那个文件夹，注意不是大文件，是做种视频的那个文件夹。 media文件绝对路径，请进入群辉file station 查看做种文件夹属性，复制所在位置后填写。
-- | --

</body>
</html>本系统只适用于群辉系统。
进入群辉系统安装docker，如果已安装docker可以略过此步骤。选择套件，设置套件来源，添加https://packages.synocommunity.com/

进入套件后，搜索docker ，选择安装。

安装docker后，进入docker，注册表搜索ptools ，会出现blllicn/ptools，选择最新版安装，目前是v0.3版本。

docker里点击映像，选择blllicn/ptools安装。
安装后，进入容器界面，点击blllicn/ptools选择编辑，如下设置

其中media是媒体库文件夹位置，就是选择需要做种的文件夹的位置。/log是日志，/db是数据库，这两个文件自己随意建立个文件夹就可以。
注意，装载路径请按照图上的输入，不要更换装载路径，文件夹选择可以根据自己实际选择。

其他设置不变，点击应用后选择启动。
输入nas IP地址加8000端口，即可进入发种鸡界面，默认用户名和密码是admin。
点击seeder，增加task

安装要求，填写标题名称，制作组后缀，豆瓣和imdb链接，种子类型按照实际填写，分季和合集按照实际填写。

file paths 选择做种的那个文件夹，注意不是大文件，是做种视频的那个文件夹。
media文件绝对路径，请进入群辉file station 查看做种文件夹属性，复制所在位置后填写。

**Comment by wzshiming** [comment]
本次不予支持加入白名单可能有以下原因

- 这个镜像不是受认证的, 也没提供要求的信息
- 只有构建产物没有源码的
- 不是正经的开源项目
- 项目 ⭐️ 过低的
- 仅为国内用户服务的镜像 (绕一圈没必要)
- 涉及魔法/科学, 盗版等...

请补全后再试 或者 推荐尝试 #2328 里其他源
