### ISSUE TITLE
docker.io/wurstmeister/kafka:2.13-2.6.0

### ISSUE THREAD

**Issue by qiuchen001** [DaoCloud/public-image-mirror#31394]
### 白名单级别

只需要这一个镜像 (docker.io/wurstmeister/kafka:2.13-2.6.0)

### 镜像仓库地址

https://hub.docker.com/layers/wurstmeister/kafka/2.13-2.6.0/images/sha256-1648f6c65577c946c45d162f662a6453400da4c489abae9b50cf629d117a505d?context=explore

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

**Comment by wzshiming** [comment]
本次不予支持加入白名单可能有以下原因

- 这个镜像不是受认证的, 也没提供要求的信息
- 只有构建产物没有源码的
- 不是正经的开源项目
- 项目 ⭐️ 过低的
- 仅为国内用户服务的镜像 (绕一圈没必要)
- 涉及魔法/科学, 盗版等...

请补全后再试 或者 推荐尝试 #2328 里其他源
