### ISSUE TITLE
trustpilot/beat-exporter申请白名单

### ISSUE THREAD

**Issue by Leaonly** [DaoCloud/public-image-mirror#31650]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/r/trustpilot/beat-exporter

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/trustpilot/beat-exporter

**Comment by mrtang3366** [comment]
technitium/dns-server:latest
