### ISSUE TITLE
talebook

### ISSUE THREAD

**Issue by huaxiangjun** [DaoCloud/public-image-mirror#3168]
SYNC docker.io/library/busybox:latest

**Comment by huaxiangjun** [comment]
docker.io/talebook:latest

**Comment by wzshiming** [comment]
别改标题, 看清楚内容提示

**Comment by huaxiangjun** [comment]
SYNC docker.io/talebook/talebook

**Comment by huaxiangjun** [comment]
docker.io/talebook/talebook:latest
