### ISSUE TITLE
是不是网站证书过期了？

### ISSUE THREAD

**Issue by fairok** [DaoCloud/public-image-mirror#31950]
failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-10-19T10:20:40+08:00 is after 2024-10-18T23:59:59Z

![image](https://github.com/user-attachments/assets/25974262-c6af-4528-a524-69c8e56917df)

**Comment by river666** [comment]
+1
#3        error: "failed to do request: Head \"https://docker.m.daocloud.io/v2/library/openjdk/manifests/11.0.16-jdk?ns=docker.io\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-10-19T10:45:46+08:00 is after 2024-10-18T23:59:59Z"

**Comment by wzshiming** [comment]
修复了
