### ISSUE TITLE
Add kubeflow:v1.7 related images

### ISSUE THREAD

**Issue by xyc1998** [DaoCloud/public-image-mirror#320]
gcr.io/arrikto/kubeflow/oidc-authservice

gcr.io/ml-pipeline/api-server
gcr.io/ml-pipeline/cache-server
gcr.io/ml-pipeline/frontend
gcr.io/ml-pipeline/metadata-writer
gcr.io/ml-pipeline/minio
gcr.io/ml-pipeline/mysql
gcr.io/ml-pipeline/persistenceagent
gcr.io/ml-pipeline/scheduledworkflow
gcr.io/ml-pipeline/viewer-crd-controller
gcr.io/ml-pipeline/visualization-server
gcr.io/ml-pipeline/workflow-controller
gcr.io/tfx-oss-public/ml_metadata_store_server
docker.io/kubeflowkatib/enas-cnn-cifar10-cpu
docker.io/kubeflowkatib/katib-controller
docker.io/kubeflowkatib/katib-db-manager
docker.io/kubeflowkatib/katib-ui
docker.io/kubeflowkatib/mxnet-mnist
docker.io/kubeflowkatib/pytorch-mnist-cpu
docker.io/kubeflownotebookswg/centraldashboard
docker.io/kubeflownotebookswg/jupyter-web-app
docker.io/kubeflownotebookswg/kfam
docker.io/kubeflownotebookswg/notebook-controller
docker.io/kubeflownotebookswg/poddefaults-webhook
docker.io/kubeflownotebookswg/profile-controller
docker.io/kubeflownotebookswg/tensorboard-controller
docker.io/kubeflownotebookswg/tensorboards-web-app
docker.io/kubeflownotebookswg/volumes-web-app
docker.io/metacontrollerio/metacontroller
docker.io/seldonio/mlserver

**Comment by xyc1998** [comment]
Have a question: How can I request a PR? I ran into this problem.
```
ERROR: Permission to DaoCloud/public-image-mirror.git denied to xyc1998.
fatal: Could not read from remote repository.
```

**Comment by wzshiming** [comment]
You should fork the repo and push to a branch of forked repo
btw you can just pull the image you want, there's no need to add it to the sync

**Comment by xyc1998** [comment]
> You should fork the repo and push to a branch of forked repo
> btw you can just pull the image you want, there's no need to add it to the sync

Thanks! But it seems I cannot pull the images above. They aren’t included in the  mirror.txt.

**Comment by wzshiming** [comment]
``` 
skopeo list-tags docker://m.daocloud.io/gcr.io/ml-pipeline/mysql  
{
    "Repository": "m.daocloud.io/gcr.io/ml-pipeline/mysql",
    "Tags": [
        "5.6",
        "5.7",
        "5.7-debian",
        "5.7.37",
        "5.7.38-debian",
        "8.0",
        "8.0-debian",
        "8.0.26",
        "8.0.3"
    ]
}
 
```

`docker pull m.daocloud.io/gcr.io/ml-pipeline/mysql:5.6`
