### ISSUE TITLE
pull image very slow

### ISSUE THREAD

**Issue by cyxinda** [DaoCloud/public-image-mirror#323]
I pull the image of [docker.m.daocloud.io/redis:7.2-rc2-bookworm],the pull rate of the part layer[layer-sha256:edc694ca19a6c032cd855e0b47af01def1a682deb1fb14bf1e417437ab7c69c3] is very slow.
And the other parts are both very fast.
I don't know why the slow rate.
![1111](https://github.com/DaoCloud/public-image-mirror/assets/7237898/6ce659e0-5262-4e5c-8d8c-c63677c117b0)
I don't think it is because local network.

**Comment by wzshiming** [comment]
这是由于我们的国际带宽有限, 如果同时的拉取很多的话是会导致这个情况, 但是只要拉了一次就有缓存了就会快很多.

**Comment by wzshiming** [comment]
今天服务提升了带宽
/close

**Comment by wzshiming** [comment]
添加了[单个镜像主动同步](https://github.com/DaoCloud/public-image-mirror?tab=readme-ov-file#%E5%8D%95%E6%AC%A1%E5%8D%95%E9%95%9C%E5%83%8F%E5%90%8C%E6%AD%A5)的机制, 对于懒加载慢的可以触发一次
