### ISSUE TITLE
ikiler/dinky

### ISSUE THREAD

**Issue by wming193** [DaoCloud/public-image-mirror#32313]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

ikiler/dinky:1.0.3-flink1.17

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/DataLinkDC/dinky

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

dinky的docker compose部署
https://github.com/DataLinkDC/dinky/blob/1.1.0/deploy/docker/docker-compose.yml

**Comment by wzshiming** [comment]
https://hub.docker.com/r/ikiler/dinky

镜像不存在
