### ISSUE TITLE
添加 docker.getcollate.io/openmetadata 镜像到白名单中

### ISSUE THREAD

**Issue by marc-pan** [DaoCloud/public-image-mirror#32379]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

https://docker.getcollate.io/openmetadata

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/open-metadata/OpenMetadata

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

官方安装文档：https://docs.open-metadata.org/latest/quick-start/local-docker-deployment
官方docker compose文件地址: 
https://github.com/open-metadata/OpenMetadata/releases/download/1.5.7-release/docker-compose.yml
https://github.com/open-metadata/OpenMetadata/releases/download/1.5.7-release/docker-compose-postgres.yml

**Comment by wzshiming** [comment]
已经在白名单了
