### ISSUE TITLE
可以利用 github action 把镜像同步到国内阿里云或其他云

### ISSUE THREAD

**Issue by yaming116** [DaoCloud/public-image-mirror#3362]
项目链接地址，在原项目基础增加了群机器人通知 ：
https://github.com/yaming116/docker-pull-proxy

详细教程可以看这里：
https://mp.weixin.qq.com/s/2DAeKY2bYCTTxFHIJnJrig

**Comment by wzshiming** [comment]
这种方式 还是非常适合个人用户的 分流一波 👍🏻
