### ISSUE TITLE
storage.k8s.io 和docker.io/openebs下面的全部插件和驱动 找不着

### ISSUE THREAD

**Issue by afrojewelz** [DaoCloud/public-image-mirror#349]
storage.k8s.io 和docker.io/openebs下面的全部插件和驱动 我grep了一下好像没有收录齐全 是否有必要收录一下？
我找到了Openebs的部分插件 新的zfs-csi-driver好像没进来导致插件安装缓慢

**Comment by afrojewelz** [comment]
Failed to load logs: container "openebs-zfs-plugin" in pod "openebs-zfs-node-vr7mp" is waiting to start: trying and failing to pull image
Reason: BadRequest (400)

**Comment by wzshiming** [comment]
支持懒加载的, 不需要加到列表可以直接用
