### ISSUE TITLE
karmada-web-api镜像同步

### ISSUE THREAD

**Issue by zyb-svn** [DaoCloud/public-image-mirror#34946]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

https://hub.docker.com/r/karmada/karmada-dashboard-api

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

### 项目源码地址 或 组织地址

https://github.com/karmada-io/dashboard

**Comment by wzshiming** [comment]
已经在白名单了
