### ISSUE TITLE
docker.io/minio/minio

### ISSUE THREAD

**Issue by samfor12** [DaoCloud/public-image-mirror#35229]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

docker.io/minio/minio

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://minio.org.cn/
由MinIO中文技术支持：北京京厂科技有限公司

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://www.minio.org.cn/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html

### 补充说明

该镜像可信且使用了
专为按照 GNU AGPL v3 许可证构建开源应用程序并能够支持自己的开发人员而设计。 它功能齐全。 如果您通过网络分发、托管或创建 MinIO 软件的衍生作品，则需要 GNU AGPL v3 许可证 您还根据相同的 GNU AGPL v3 许可证发布了组合作品的完整、相应的源代码。 此要求适用 无论你是否修改了 MinIO。

**Comment by wzshiming** [comment]
已经在白名单了
