### ISSUE TITLE
[Question] 拉镜像的时候报错 401 Unauthorized

### ISSUE THREAD

**Issue by Jixiangup** [DaoCloud/public-image-mirror#35515]
### 原始异常

```
failed to solve: m.daocloud.io/docker.io/library/openjdk:17: pulling from host m.daocloud.io failed with status code [manifests 17]: 401 Unauthorized
```

![image](https://github.com/user-attachments/assets/90b97f9e-42b2-4d9a-9e6e-d50231489659)

**Comment by wzshiming** [comment]
我看了下日志是 token 超时了..., 但是我无法复现, 尝试升级 buildx 感觉是版本太旧没有更新 token

**Comment by wzshiming** [comment]
我看了下日志是 token 超时了..., 但是我无法复现, 尝试升级 buildx 感觉是版本太旧没有更新 token

**Comment by Jixiangup** [comment]
> 我看了下日志是 token 超时了..., 但是我无法复现, 建议尝试升级 buildx 感觉是版本太旧没有更新 token

新装的环境理论上不会吧～

**Comment by wzshiming** [comment]
建议直接pull 一下，我感觉是软件源版本低了

**Comment by Jixiangup** [comment]
比较藕现 隔一天可能又解决了 因为我自己有科学方案解决 所以暂时先不管
或者我使用了 其他产品 这里不贴出来了 没有调研过不排除镜像被二改可能 所以大家遇到同样问题考虑一下科学解决 或者尝试其他镜像吧 我就关了这个issue了
