### ISSUE TITLE
增加白名单

### ISSUE THREAD

**Issue by EayonLee** [DaoCloud/public-image-mirror#36212]
### 白名单级别

只需要这一个镜像 (如 docker.io/library/busybox)

### 镜像仓库地址

https://hub.docker.com/layers/clickhouse/clickhouse-server/24.5.1.1763/images/sha256-bd3228d52b174b0360fddd547f2f11cc02e335bda567fc24c312230b3da4b6e0?context=explore

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

不是 - 请补充下面的信息

### 项目源码地址 或 组织地址

https://github.com/ClickHouse/ClickHouse

### 官网 或 文档 或 项目源码 中哪提及对应的镜像的地址 (需要证明这个镜像和源码有实际关联)

https://github.com/ClickHouse/ClickHouse

### 补充说明

目前只需要clickhouse:24.5.1.1763的arm64v8版本

**Comment by wzshiming** [comment]
已经在白名单了, 请看文档了解怎么使用
