### ISSUE TITLE
SYNC IMAGE nvcr.io/nvidia/k8s-device-plugin:v0.14.1

### ISSUE THREAD

**Issue by NierYYDS** [DaoCloud/public-image-mirror#366]
SYNC nvcr.io/nvidia/k8s-device-plugin:v0.14.1

**Comment by wzshiming** [comment]
已手动给同步, 标题是固定的哦

https://github.com/DaoCloud/public-image-mirror/blob/180c3da9bbcf22109580f4b40411acd4e3e62470/.github/workflows/target-image-sync.yml#L14

/close
