### ISSUE TITLE
docker仓库申请

### ISSUE THREAD

**Issue by zhyreng** [DaoCloud/public-image-mirror#36729]
### 白名单级别

需要这个组织下所有镜像 (如 docker.io/library/*)

### 镜像仓库地址

https://docker.m.daocloud.io

### 这是 **镜像仓库** 认证可信的 **验证过的发布者(Verified Publisher)**或者**赞助的项目(Sponsored OSS)** 么?

是的 - 不需要填下面的信息 - 如果实际上不是将不再继续核查

**Comment by wzshiming** [comment]
你要做啥?

**Comment by zhyreng** [comment]
群晖的docker仓库不能用了。按照这个仓库的要求申请使用这个仓库

**Comment by wzshiming** [comment]
https://docker.m.daocloud.io/ 就是这个仓库提供的.

**Comment by zhyreng** [comment]
昨天拉取镜像的时候提示需要白名单啥的

**Comment by wzshiming** [comment]
https://github.com/DaoCloud/public-image-mirror/issues/2328 看这
