### ISSUE TITLE
屏蔽的 Image 列表

### ISSUE THREAD

**Issue by wzshiming** [DaoCloud/public-image-mirror#3698]
由于被频繁拉取超大的同一个 Image 刷爆流量, 现在暂时放入黑名单, 等未来支持单镜像限流之后再说

**Comment by starxinguo** [comment]
rancher/mirrored-flannelcni-flannel:v0.17.0

**Comment by wzshiming** [comment]
从黑名单机制转向了白名单 https://github.com/DaoCloud/public-image-mirror/issues/2328
