### ISSUE TITLE
对于比较大的Layer经常会拉取失败

### ISSUE THREAD

**Issue by muma378** [DaoCloud/public-image-mirror#390]
![WeChatWorkScreenshot_960435f3-2c74-4430-bb2c-d52b9f3cf85f](https://github.com/DaoCloud/public-image-mirror/assets/1912689/815caa13-882c-4e2a-9e52-eea86ad9eb71)

如图所示，我非常确定 `m.daocloud.io/docker.io/amambadev/jenkins-agent-base:v0.3.0` 这个镜像已经同步过了（也按照文档手动同步过了 #387 ），但是拉取的时候还是经常会报 Unexpected EOF，速度也只有几百K，是否是服务供应商对于大文件的带宽限制？

**Comment by wzshiming** [comment]
<img width="888" alt="image" src="https://github.com/DaoCloud/public-image-mirror/assets/6565744/c9d75937-4e68-43b7-90c6-0b59c33801f6">

![image](https://github.com/DaoCloud/public-image-mirror/assets/6565744/3bcf64a6-9790-48a5-adaa-051105934b42)

看起来有个 layer 一直同步失败导致的, 没有缓存, 每次都走懒加载

**Comment by wzshiming** [comment]
我手动检查了一下 这个 layer 的数据是已经下载好了的, 但是没有冲 _upload 移动到  blobs,  应该是这一步出错了

**Comment by wzshiming** [comment]
/assign @yankay

我们有没有可能换个服务供应商

**Comment by yankay** [comment]
> /assign @yankay
> 
> 我们有没有可能换个服务供应商

我觉得可以，有没有更合适的 :-)

**Comment by wzshiming** [comment]
我想了2个方案
1. 迁移到 aliyun OSS, registry 在 v2 里有现成的[驱动](https://github.com/distribution/distribution/blob/release/2.8/registry/storage/driver/oss/oss.go), 可以避免当前先把 us3 当文件系统挂载然后再使用的尴尬, 虽然这个驱动在下个 v3 版本会被移除
2. [crproxy](https://github.com/wzshiming/crproxy/tree/master) 在当前做聚合多个 registry 的项目中加入 cache, redirect, 以及主动同步指定 cache 的能力, 就可以直接去掉中间层对接需要的 cache 对当前场景进行优化, 也方便调试

**Comment by wzshiming** [comment]
ucloud:
[免费入带宽 50 Mbps](https://docs.ucloud.cn/unet/eip/introduction?id=%e5%85%a5%e5%8f%a3%e5%b8%a6%e5%ae%bd%e5%85%8d%e8%b4%b9%e9%a2%9d%e5%ba%a6)
[us3](https://docs.ucloud.cn/ufile/bill/billing)
出带宽
- 10Mbps/月 531.25元
- 20Mbps/月 1381.25元

- 存储 0.004 元/GB/天
- 流量 00:00-08:00（闲时）：0.25 元/GB, 08:00-24:00（忙时）：0.45 元/GB
- 请求 0.01 元/万次

aliyun:
[免费入带宽 10 Mbit/s](https://help.aliyun.com/zh/ecs/inbound-and-outbound-bandwidth-of-ecs-instances?spm=a2c4g.11186623.0.i18)
出带宽
- 10Mbps/月 525元
- 20Mbps/月 1325元

[oss](https://www.aliyun.com/price/product?spm=a2c4g.11186623.0.0.e2673c852DnSCb&5176.7933691.744462.price2.b7a36a56kldoxf#/oss/detail/ossbag)
- 存储 0.12 元/GB/月 (除以 30, 也是 0.004 元/GB/天)
- 流量 00:00-08:00（闲时）：0.25元/GB, 08:00-24:00（忙时）：0.50元/GB
- 请求 0.01元/万次

**Comment by wzshiming** [comment]
总的来说

- aliyun 还有 oss 存储包流量包会优惠挺多的, ucloud 没有优惠
- aliyun 入网带宽是个劣势, 不过我们可以换个思路
  - 对比当前 ucloud 上的服务器是
    - 1c8g 179.35元
    - 出带宽 12M 701.25元
    - 入带宽 50M
  - 买 4 台 1c1g 1m 机器, 1台 1c1g 12m 的作为入口, 我们就获得了 50Mbps 的入带宽
    - 1c1g * 5, 115 元
    - 出带宽 12M 作为入口(1m * 4 + 12m * 1 合计 152 + 723), 12M 875 元
    - 入带宽 50M
  - 或者 买 5 台 1c1g 5m 机器, 使用域名做负载均衡, 同样 50Mbps 的入带宽 (aliyun 带宽超过 5m 之后价格飞涨)
    - 出带宽 5m * 5 都作为入口(125 * 5), 25M(合计带宽) 625 元

**Comment by wzshiming** [comment]
/close

供应商迁移完毕, 这类同步失败的问题已经解决
