### ISSUE TITLE
建个群让大家交流怎么样

### ISSUE THREAD

**Issue by sudo888samewick** [DaoCloud/public-image-mirror#4101]
我觉得可以创建一个交流群，这样大家有想要的镜像或者使用镜像时遇到什么问题，就可以直接现在群里反映

![image](https://github.com/DaoCloud/public-image-mirror/assets/150644414/243d5c5d-467f-414a-b54d-f943da653615)

**Comment by wzshiming** [comment]
#4183 建了

**Comment by tdouguo** [comment]
群二维码需要邀请 方便拉一下嘛 vvvgjm

**Comment by YiMoWanXia** [comment]
拉一下 +1

**Comment by Eddie-0721** [comment]
二维码失效了，可否给个wx号，我们加一下，谢谢大佬

**Comment by xiangxingze** [comment]
二维码失效了，可否给个wx号

**Comment by GhostBone** [comment]
qq的会好些，微信大型群不方便管理
