### ISSUE TITLE
Can't pull m.daocloud.io/kong:3.6

### ISSUE THREAD

**Issue by XYDSDS** [DaoCloud/public-image-mirror#5037]
docker pull m.daocloud.io/kong:3.6
Error response from daemon: Get "https://m.daocloud.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by wzshiming** [comment]
请确定具体的 registry 和 repo 

https://github.com/DaoCloud/public-image-mirror/issues/new?assignees=&labels=sync+image&projects=&template=sync-image.yml
