### ISSUE TITLE
superng6/qbittorrentee:latest

### ISSUE THREAD

**Issue by tuanzhi666** [DaoCloud/public-image-mirror#6091]
superng6/qbittorrentee:latest

**Comment by wzshiming** [comment]
请依据模板 https://github.com/DaoCloud/public-image-mirror/issues/new?assignees=&labels=sync+image&projects=&template=sync-image.yml

**Comment by tuanzhi666** [comment]
docker.io/superng6/qbittorrentee:latest

**Comment by tuanzhi666** [comment]
docker.io/superng6/qbittorrentee:latest
