### ISSUE TITLE
[已生效] 限流 & 降级

### ISSUE THREAD

**Issue by wzshiming** [DaoCloud/public-image-mirror#6196]
- 当前 blob(镜像层) 限流
  - 1024Ki/s (下载 1Mi 会先 sleep 1s 再响应, 下载 10Mi 会先 sleep 10s 再响应, 下载 1Gi 会先 sleep 20min 再响应 以此类推...)
- 当前 IP 限流
  - 并发限制 10 (请调低 Docker 拉取并发数, 其默认值应该为 3) (超出响应 429)
  - 20r/m (每分钟20个请求) (超出响应 429)
  - 1Gi/2h (小于 1Gi 的 blob 每2小时能获取多个, 否则每2小时只能获取一个, 达到限额将会卡住等时间到了然后再继续)

- 禁用 `_catalog` (获取全部镜像)
- 禁用 `tags/list` (获取镜像全部 tag)

**Comment by chinfeng** [comment]
超大型镜像如 gitlab 镜像的时候卡壳了，不停的 retry/timeout 之间鬼畜，估计是限流政策引起

**Comment by wzshiming** [comment]
> 超大型镜像如 gitlab 镜像的时候卡壳了，不停的 retry/timeout 之间鬼畜，估计是限流政策引起

如果拉取镜像等待超时的确会有这个问题, 我没想到比较好的, 限流和大镜像两者都能照顾到的方法

**Comment by LemonK626** [comment]
docker.io/xiaoyaliu/xiaoyaalist:latest

**Comment by LemonK626** [comment]
docker.io/xiaoyaliu/alist:latest

**Comment by linonetwo** [comment]
@chinfeng 你找到下载gitlab的可用的镜像源了吗

**Comment by chinfeng** [comment]
> @chinfeng 你找到下载gitlab的可用的镜像源了吗

没找到，只能自己搭一个了。话说这次的全面封杀是不是因为 `xijinping615/xi-jinping-tts` 这个镜像被发现了？

**Comment by linonetwo** [comment]
不知道，我不关心这些文科的东西，好好做自己的产品比花时间在别的人身上有意义。

我现在是用一台 Window 服务器启动 clash，供本地所有服务器翻墙，参见 https://www.711214.xyz/951/

**Comment by wzshiming** [comment]
合并入 #2328
/close
