### ISSUE TITLE
docker.io/hispark/qiankunbp:1.0.0

### ISSUE THREAD

**Issue by Porlain** [DaoCloud/public-image-mirror#7542]
IMAGE SYNC

**Comment by rotorliu** [comment]
Error response from daemon: pull access denied for m.daocloud.io/docker.io/hispark/qiankunbp, repository does not exist or may require 'docker login': denied: 🚫 这镜像不在白名单. this image is not in the allowlist. 📦 https://github.com/DaoCloud/public-image-mirror/issues/2328 🔗
