### ISSUE TITLE
智能 inject 镜像地址。

### ISSUE THREAD

**Issue by yankay** [DaoCloud/public-image-mirror#83]
例如 ： https://istio.io/latest/docs/setup/getting-started/#dashboard。
有很多情况是需要 运行 类似 `$ kubectl apply -f samples/addons` 的命令的。

在这样的情况下，需要手动打开文件，一个个的比对修改，比较麻烦。
如果能够自动化的完成，比如 

就很 厉害了

**Comment by wzshiming** [comment]
https://github.com/DaoCloud/public-image-mirror/blob/004088b20a0809c63710a9c3d932293d3b5b207a/README.md?plain=1#L70-L78

这个已经实现了, 也加到 README 了

**Comment by wzshiming** [comment]
单个文件直接 `cat ./deploy.yaml | ./image-filter.sh | kubectl apply -f - `

**Comment by yankay** [comment]
Got It. 没有仔细看 readme。牛逼
